name: Windows

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      TARGET_VERSION:
        description: "目标版本"
        type: string
        default: "7.4"
        required: false
  push:
    branches:
      - "main"
      - "releases/**"
    tags:
      - v*

jobs:
  Compile:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "cheat-engine/cheat-engine"
          ref: ${{ inputs.TARGET_VERSION }}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        shell: cmd
        run: msbuild /t:clean /t:build DBKKernel\DBKKernel.vcxproj /p:Configuration="Release without sig" /p:Platform=x64 /p:PostBuildEventUseInBuild=false

      - name: Upload To Artifact_Global
        uses: actions/upload-artifact@main
        with:
          name: ${{ github.job }}
          path: Cheat Engine\bin
